name: Terraform CI/CD

on:
  pull_request:
    branches: [ ashwini ]
  push:
    branches: [ ashwini ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: live/dev/vpc

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
      - run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve